from __future__ import annotations

from typing import Any

FIXTURE_PROSPECTS: list[dict[str, Any]] = [
    {
        "business_name": "Riverside Repairs",
        "category": "Appliance repair service",
        "location": "Dublin 8, Ireland",
        "place_id": "fixture-riverside-repairs",
        "website_url": None,
        "footprint": "absent",
        "qualification_reason": "No owned website found; local customers lack a clear service and enquiry page.",
        "review_themes": ["quick response", "clear explanations", "reliable local service"],
        "audit": {
            "reachable": False,
            "https": False,
            "mobile_meta": False,
            "clear_cta": False,
            "contact_visible": False,
            "lead_form": False,
            "findings": ["No owned website was identified."],
            "score": 5,
        },
        "opportunity_score": 93,
        "palette": {"ink": "#17251f", "brand": "#ef6c3e", "accent": "#f6c85f", "paper": "#fffaf3"},
    },
    {
        "business_name": "North Star Dog Grooming",
        "category": "Pet groomer",
        "location": "Dublin 7, Ireland",
        "place_id": "fixture-north-star-grooming",
        "website_url": "https://instagram.com/example-north-star",
        "footprint": "social_only",
        "qualification_reason": "The current footprint is social-only, making service details and conversion paths hard to control.",
        "review_themes": ["calm with nervous pets", "friendly care", "consistent grooming"],
        "audit": {
            "reachable": True,
            "https": True,
            "mobile_meta": True,
            "clear_cta": False,
            "contact_visible": False,
            "lead_form": False,
            "findings": ["Social profile only", "No owned service or enquiry page"],
            "score": 32,
        },
        "opportunity_score": 87,
        "palette": {"ink": "#16223a", "brand": "#6e56cf", "accent": "#f6b8d1", "paper": "#fbf9ff"},
    },
    {
        "business_name": "Harbour Bloom Florals",
        "category": "Florist",
        "location": "Dublin 2, Ireland",
        "place_id": "fixture-harbour-bloom",
        "website_url": "https://example.com/harbour-bloom-old",
        "footprint": "weak",
        "qualification_reason": "An owned site exists but lacks a clear mobile enquiry path and visible service proposition.",
        "review_themes": ["thoughtful arrangements", "seasonal creativity", "helpful personal service"],
        "audit": {
            "reachable": True,
            "https": True,
            "mobile_meta": False,
            "clear_cta": False,
            "contact_visible": True,
            "lead_form": False,
            "findings": ["Missing mobile viewport metadata", "No primary call to action", "Contact details are buried"],
            "score": 46,
        },
        "opportunity_score": 78,
        "palette": {"ink": "#26352f", "brand": "#be4b6d", "accent": "#e8b866", "paper": "#fff9f4"},
    },
]
